# Generated by Django 4.2 on 2024-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.hashtag'),
        ),
    ]
