# Generated by Django 4.2 on 2024-04-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='products.hashtag'),
        ),
    ]
