# Generated by Django 4.2 on 2024-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0003_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jjim',
            field=models.ManyToManyField(related_name='jjimed', to='products.products'),
        ),
    ]
