# Generated by Django 4.2 on 2024-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_jjim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='./static/image/default_profile.png', upload_to=''),
        ),
    ]
